[server]
maxUploadSize = 2048
maxMessageSize = 2048

[client]
showSidebarNavigation = true

[theme]
base = "dark"
primaryColor = "#22c55e"
backgroundColor = "#0b1020"
secondaryBackgroundColor = "#131a2b"
textColor = "#e5e7eb"
font = "sans serif"
